// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAyl-EiBXROblUNlbYua9N1Bx2dV-UXJik',
    appId: '1:406602129912:web:41422d275f042fa90fb60d',
    messagingSenderId: '406602129912',
    projectId: 'heartpital-f867a',
    authDomain: 'heartpital-f867a.firebaseapp.com',
    storageBucket: 'heartpital-f867a.firebasestorage.app',
    measurementId: 'G-PS515GXBV4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDn_w0LuF5AT3_8p8lV8-TORcUX0uGbxLw',
    appId: '1:406602129912:android:ce18965cafb66f430fb60d',
    messagingSenderId: '406602129912',
    projectId: 'heartpital-f867a',
    storageBucket: 'heartpital-f867a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4uQJwHewUT44znPd4T1TfS61TUNGBoxI',
    appId: '1:406602129912:ios:d634b5b74b786ed30fb60d',
    messagingSenderId: '406602129912',
    projectId: 'heartpital-f867a',
    storageBucket: 'heartpital-f867a.firebasestorage.app',
    iosBundleId: 'com.example.heartpitalV1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC4uQJwHewUT44znPd4T1TfS61TUNGBoxI',
    appId: '1:406602129912:ios:d634b5b74b786ed30fb60d',
    messagingSenderId: '406602129912',
    projectId: 'heartpital-f867a',
    storageBucket: 'heartpital-f867a.firebasestorage.app',
    iosBundleId: 'com.example.heartpitalV1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAyl-EiBXROblUNlbYua9N1Bx2dV-UXJik',
    appId: '1:406602129912:web:4f1298a96c7181e60fb60d',
    messagingSenderId: '406602129912',
    projectId: 'heartpital-f867a',
    authDomain: 'heartpital-f867a.firebaseapp.com',
    storageBucket: 'heartpital-f867a.firebasestorage.app',
    measurementId: 'G-LDGKWN9E4P',
  );
}
